// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DockerBuild
{
    [DockerBuildResourceType("pulumi:providers:docker-build")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The build daemon's address.
        /// </summary>
        [Output("host")]
        public Output<string?> Host { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("docker-build", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github.com/pulumi/pulumi-docker-build",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The build daemon's address.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("registries", json: true)]
        private InputList<Inputs.RegistryArgs>? _registries;
        public InputList<Inputs.RegistryArgs> Registries
        {
            get => _registries ?? (_registries = new InputList<Inputs.RegistryArgs>());
            set => _registries = value;
        }

        public ProviderArgs()
        {
            Host = Utilities.GetEnv("DOCKER_HOST") ?? "";
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
