// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dockerbuild;

import com.pulumi.core.TypeShape;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dockerbuild.inputs.Registry;
import java.lang.String;
import java.util.List;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("docker-build");
/**
 * The build daemon&#39;s address.
 * 
 */
    public Optional<String> host() {
        return Codegen.stringProp("host").config(config).env("DOCKER_HOST").def("").get();
    }
    public Optional<List<Registry>> registries() {
        return Codegen.objectProp("registries", TypeShape.<List<Registry>>builder(List.class).addParameter(Registry.class).build()).config(config).get();
    }
}
