// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("docker-build");

/**
 * The build daemon's address.
 */
export declare const host: string;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host") ?? (utilities.getEnv("DOCKER_HOST") || "");
    },
    enumerable: true,
});

export declare const registries: outputs.Registry[] | undefined;
Object.defineProperty(exports, "registries", {
    get() {
        return __config.getObject<outputs.Registry[]>("registries");
    },
    enumerable: true,
});

