// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DockerBuild.Outputs
{

    [OutputType]
    public sealed class BuilderConfig
    {
        /// <summary>
        /// Name of an existing buildx builder to use.
        /// 
        /// Only `docker-container`, `kubernetes`, or `remote` drivers are
        /// supported. The legacy `docker` driver is not supported.
        /// 
        /// Equivalent to Docker's `--builder` flag.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private BuilderConfig(string? name)
        {
            Name = name;
        }
    }
}
