// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DockerBuild.Outputs
{

    [OutputType]
    public sealed class CacheFromRegistry
    {
        /// <summary>
        /// Fully qualified name of the cache image to import.
        /// </summary>
        public readonly string Ref;

        [OutputConstructor]
        private CacheFromRegistry(string @ref)
        {
            Ref = @ref;
        }
    }
}
