// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DockerBuild.Outputs
{

    [OutputType]
    public sealed class CacheToAzureBlob
    {
        /// <summary>
        /// Base URL of the storage account.
        /// </summary>
        public readonly string? AccountUrl;
        /// <summary>
        /// Ignore errors caused by failed cache exports.
        /// </summary>
        public readonly bool? IgnoreError;
        /// <summary>
        /// The cache mode to use. Defaults to `min`.
        /// </summary>
        public readonly Pulumi.DockerBuild.CacheMode? Mode;
        /// <summary>
        /// The name of the cache image.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Blob storage account key.
        /// </summary>
        public readonly string? SecretAccessKey;

        [OutputConstructor]
        private CacheToAzureBlob(
            string? accountUrl,

            bool? ignoreError,

            Pulumi.DockerBuild.CacheMode? mode,

            string name,

            string? secretAccessKey)
        {
            AccountUrl = accountUrl;
            IgnoreError = ignoreError;
            Mode = mode;
            Name = name;
            SecretAccessKey = secretAccessKey;
        }
    }
}
