// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DockerBuild.Outputs
{

    /// <summary>
    /// Recommended for use with GitHub Actions workflows.
    /// 
    ///   	An action like crazy-max/ghaction-github-runtime is recommended to expose
    /// appropriate credentials to your GitHub workflow.
    /// </summary>
    [OutputType]
    public sealed class CacheFromGitHubActions
    {
        /// <summary>
        /// The scope to use for cache keys. Defaults to `buildkit`.
        /// 
        /// This should be set if building and caching multiple images in one
        /// workflow, otherwise caches will overwrite each other.
        /// </summary>
        public readonly string? Scope;

        [OutputConstructor]
        private CacheFromGitHubActions(string? scope)
        {
            Scope = scope;
        }
    }
}
