// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dockerbuild.inputs;




public final class ExportCacheOnlyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ExportCacheOnlyArgs Empty = new ExportCacheOnlyArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private ExportCacheOnlyArgs $;

        public Builder() {
            $ = new ExportCacheOnlyArgs();
        }
        public ExportCacheOnlyArgs build() {
            return $;
        }
    }

}
