# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from .. import outputs as _root_outputs

import types

__config__ = pulumi.Config('dockerbuild')


class _ExportableConfig(types.ModuleType):
    @property
    def host(self) -> str:
        """
        The build daemon's address.
        """
        return __config__.get('host') or (_utilities.get_env('DOCKER_HOST') or '')

    @property
    def registries(self) -> Optional[str]:
        return __config__.get('registries')

